import Vue from 'vue';

import cmpMenu from '@/components/ui/menu';
import cmpDrawer from '@/components/ui/navdrawer';
import cmpAlert from '@/components/ui/alert';
import cmpFooter from '@/components/ui/footer';
import cmpAsk from '@/components/ask/askform';
import cmpToast from '@/components/ui/toast';
import cmpLoading from '@/components/ui/loading';
import cmpPanel from '@/components/ui/panel';
import cmpTooltip from '@/components/ui/tooltip';
import cmpNotifications from '@/components/ui/notifications';
import cmpNotificationItem from '@/components/ui/notificationitem';
import cmpFileUpload from '@/components/ui/fileupload';
import cmpSellProfile from '@/components/ui/sellprofile';
import cmpLocaleSelect from '@/components/ui/localeselect';

Vue.component('app-menu', cmpMenu);
Vue.component('app-navdrawer', cmpDrawer);
Vue.component('app-alert', cmpAlert);
Vue.component('app-footer', cmpFooter);
Vue.component('app-panel', cmpPanel);
Vue.component('app-ask', cmpAsk);
Vue.component('app-toast', cmpToast);
Vue.component('app-loading', cmpLoading);
Vue.component('app-tooltip', cmpTooltip);
Vue.component('app-notifications', cmpNotifications);
Vue.component('app-notification-item', cmpNotificationItem);
Vue.component('app-file-upload', cmpFileUpload);
Vue.component('app-sell-profile', cmpSellProfile);
Vue.component('app-select-location', cmpLocaleSelect);